# Crowdsec Bouncer Configuration
api_key: <CROWDSEC_BOUNCER_API_KEY>
agent_url: http://127.0.0.1:8080
# How frequently to request decision deltas from CrowdSec's stream endpoint.
stream_update_frequency: 10s
# Log level for the bouncer, options: trace, debug, info, warning, error
log_level: warning
# Set to true if zoraxy is proxied behind Cloudflare
is_proxied_behind_cloudflare: true
# IP address display in Recent Blocked Connections: masked (default) or full
blocked_events_ip_mode: masked
